### ISSUE TITLE
undefined constant SQLite3::Database

### ISSUE THREAD

**Issue by crisward** [drujensen/kemalyst-model#6]
I'm very new to Crystal, so apologies if this is silly question. 

I'm getting the below error

``` bash
Error in ./libs/kemalyst-model/adapter/sqlite.cr:6: undefined constant SQLite3::Database

  @pool : ConnectionPool(SQLite3::Database)
                         ^~~~~~~~~~~~~~~~~
```

shards.yml

``` yml
dependencies:
  kemal:
    github: sdogruyol/kemal
    branch: master
  slang:
    github: jeromegn/slang
  kemalyst-model:
    github: drujensen/kemalyst-model
    branch: master
  sqlite3:
    github: crystal-lang/crystal-sqlite3
    branch: master
```

database.yml

``` yml
sqlite:
  database: config/test.db
```

user.cr

``` ruby
require "kemalyst-model/adapter/sqlite"

class User < Kemalyst::Model
  adapter sqlite

  # table name is set to post_comments and timestamps are disabled.
  sql_mapping({ 
    first_name: ["VARCHAR(255)", String], 
    surname: ["VARCHAR(255)", String], 
    address: ["TEXT", String],
    postcode: ["VARCHAR(255)", String]
  })

end
```

Many thanks.
